alias zc='vim $HOME/.config/zsh/zshrc'
alias vc='vim $HOME/.vimrc'
alias rc='vim $HOME/.config/ranger/rc.conf'
alias ic='vim $HOME/.config/i3/config'
alias pc='vim $HOME/.config/polybar/config'
alias gc='vim $HOME/.gitconfig'
alias gic='vim $HOME/.gitignore'
